name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t blaztted/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true blaztted/react-test npm test

      - run: docker build -t blaztted/multi-docker-client ./client
      - run: docker build -t blaztted/multi-docker-nginx ./nginx
      - run: docker build -t blaztted/multi-docker-server ./server
      - run: docker build -t blaztted/multi-docker-worker ./worker

      - run: docker push blaztted/multi-docker-client
      - run: docker push blaztted/multi-docker-nginx
      - run: docker push blaztted/multi-docker-server
      - run: docker push blaztted/multi-docker-worker
